version: "3.9"

services:
  quenary-install:
    build: php
    working_dir: /app
    command: composer install
    volumes:
      - .:/app
    profiles:
      - donotstart
    env_file:
      .env

  quenary-build:
    build: php
    working_dir: /app
    command: sh /app/example/build.sh
    volumes:
      - .:/app
    profiles:
      - donotstart
    env_file:
      .env

  quenary-run:
    build: php
    working_dir: /app
    command: php /app/example/run.php
    volumes:
      - .:/app
    profiles:
      - donotstart
    env_file:
      .env

  quenary-tests:
    build:
      context: .
      dockerfile: php/Dockerfile
    working_dir: /app
    command: sh -c "composer install && composer test"
    volumes:
      - .:/app
    profiles:
      - donotstart
    env_file:
      .env